#!/bin/sh

# kjolley
# july 2012

arduino_ip="192.168.1.132"

while true
do
  n=0
  while [ $n -lt 256 ]
  do
	echo $n
	let n=n+1
	wget -q --output-document="${n}.html" "http://${arduino_ip}/${n}"
	sleep 5
  done
done
